### ISSUE TITLE
Improve typings

### ISSUE THREAD

**Issue by ruslan-amirov-stenn** [Rutter/react-rutter-link#17]
https://github.com/Rutter/react-rutter-link/blob/main/src/types/index.ts#L38

```
export interface Rutter {
  open: Function;
  exit: Function;
  create: Function;
  destroy: Function;
}

```

'Function' is not the best way to define types of functions. 
Please specify the params and return types of them.
https://www.totaltypescript.com/dont-use-function-keyword-in-typescript

This example shows that typescript doesn't protect us from calling the open function with the wrong parameters.

```
const rutter = useRutterLink(...

rutter.open({
        platform: 'SHOPIFY',  // right key
      })

rutter.open({
        pfm: 'SHOPIFY',  // wrong key
      })

// no ts errors
```

It might cause bugs if you change these functions' signatures.

**Comment by cyrieu** [comment]
Hi Ruslan thanks for adding this issue, we'll be tracking this internally in our project management system so I will close this and follow-up directly when it is in progress.
