### ISSUE TITLE
Remove dependency on unpkg.com

### ISSUE THREAD

**Issue by barnabycollins-s2z** [Rutter/react-rutter-link#5]
Hey there,

We're using react-rutter-link in our application and have found that unpkg.com has been offline at some points today, meaning that Rutter Link is broken across all instances including production.

Would it be possible to refactor this library to import `@rutter/rutter-link-js` through package.json, rather than adding it to the page as a script element? I can see that it allows you to always use the latest version of that module, but it also makes projects using `react-rutter-link` more fragile.

Thanks for your help :) the package is great otherwise!

**Comment by cyrieu** [comment]
Hey there, we will update our CDN provider to something different to resolve this issue as soon as possible!
